### ISSUE TITLE
Error when fradle runClient

### ISSUE THREAD

**Issue by VVriter** [lambda-client/ExamplePlugin#28]
im trying to code lambda client plugin
and have interesting error when laoding client using gradle run client

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Lambda (lambda)
Caused by: java.lang.NoClassDefFoundError: org/reflections/Reflections
	at com.lambda.client.commons.utils.ClassUtils.findClasses(ClassUtils.kt:19)
	at com.lambda.client.module.ModuleManager.preLoad0(ModuleManager.kt:74)
	at com.lambda.client.module.ModuleManager.preLoad0(ModuleManager.kt:16)
	at com.lambda.client.AsyncLoader$preLoadAsync$1.invokeSuspend(Loader.kt:45)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: org.reflections.Reflections
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 13 more
Caused by: java.lang.NullPointerException

**Comment by NepNep21** [comment]
Fixed in #27 but not merged yet for whatever reason
